//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Graph.WebRole.Resources.GettingStarted {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Graph.WebRole.Resources.GettingStarted.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Quick Start.
        /// </summary>
        public static string MS_GRAPH_QUICK_START {
            get {
                return ResourceManager.GetString("MS_GRAPH_QUICK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quick start will let you try out calls, register your app, and download a sample app that connects to data using Microsoft Graph. The sample app sends an email on a user&apos;s behalf. It will show you how to authenticate and make calls to Microsoft Graph using a school or work or a Microsoft account..
        /// </summary>
        public static string MS_GRAPH_QUICK_START_DESCRIPTION {
            get {
                return ResourceManager.GetString("MS_GRAPH_QUICK_START_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Something weird has happened&lt;/h4&gt;
        ///&lt;p&gt;Please try again&lt;/p&gt;.
        /// </summary>
        public static string ON_ERROR {
            get {
                return ResourceManager.GetString("ON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a simple app that connects to Office 365 and calls the Microsoft Graph API. After you pick your platform, you&apos;ll walk through getting the right tools, registering your app, and running the code..
        /// </summary>
        public static string PICK_PLATFORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("PICK_PLATFORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You can not change the platform once an app has been registered. To change the platform, please click here to start over..
        /// </summary>
        public static string PICK_PLATFORM_NOTE {
            get {
                return ResourceManager.GetString("PICK_PLATFORM_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the platform you&apos;ll be building for.
        /// </summary>
        public static string PICK_PLATFORM_TITLE {
            get {
                return ResourceManager.GetString("PICK_PLATFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven&apos;t already, install &lt;a href=&quot;https://developer.android.com/sdk/index.html&quot; target=&quot;_blank&quot;&gt;Android Studio&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_ANDROID {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven&apos;t already, install &lt;a href=&quot;https://nodejs.org/&quot; target=&quot;_blank&quot;&gt;Node.js&lt;/a&gt; and &lt;a href=&quot;https://bower.io/&quot; target=&quot;_blank&quot;&gt;Bower&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_ANGULAR {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_ANGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven&apos;t already, install &lt;a href=&quot;https://www.visualstudio.com/vs-2015-product-editions&quot; target=&quot;_blank&quot;&gt;Visual Studio 2015 Community or Enterprise&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_DOTNET {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_DOTNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///    &lt;li&gt;1. If you haven&apos;t already, download and install Xcode on your Mac.&lt;/li&gt;
        ///    &lt;li&gt;
        ///        2. Run the following commands to install and set up the &lt;a href=&quot;http://cocoapods.org/&quot; target=&quot;_blank&quot;&gt;CocoaPods&lt;/a&gt; dependency manager.&lt;br /&gt;
        ///        &lt;b&gt;sudo gem install cocoapods&lt;/b&gt;&lt;br /&gt;
        ///        &lt;b&gt;pod setup&lt;/b&gt;
        ///    &lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_IOS {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///    &lt;li&gt;
        ///        1. Download and install Xcode on your Mac. You can find it &lt;a href=&quot;https://developer.apple.com/download/more/&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;.&lt;br /&gt;
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        2. Run the following commands to install and set up the &lt;a href=&quot;http://cocoapods.org/&quot; target=&quot;_blank&quot;&gt;CocoaPods&lt;/a&gt; dependency manager.&lt;br /&gt;
        ///        &lt;b&gt;sudo gem install cocoapods&lt;/b&gt;&lt;br /&gt;
        ///        &lt;b&gt;pod setup&lt;/b&gt;
        ///    &lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_IOS_OBJECTIVE_C {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_IOS_OBJECTIVE_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///    &lt;li&gt;
        ///        1. Download and install Xcode 7.3.1 on your Mac. You can find it &lt;a href=&quot;https://developer.apple.com/download/more/&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;.&lt;br /&gt;
        ///        &lt;p class=&quot;yellowNote&quot;&gt;&lt;b&gt;Note:&lt;/b&gt; The sample was tested on Xcode 7.3.1.  This sample does not yet support XCode 8 and iOS10, which uses the Swift 3.0 framework.&lt;/p&gt;
        ///&lt;/li&gt;
        ///    &lt;li&gt;
        ///        2. Run the following commands to install and set up the &lt;a href=&quot;http://cocoapods.org/&quot; target=&quot;_blank&quot;&gt;CocoaPods&lt;/a&gt; dependency manager. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_IOS_SWIFT {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_IOS_SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Get your favorite text editor. You can write JavaScript in many different IDEs and since none provide a significant advantage for developing with the Office 365 APIs, choose your favorite and get started. [Brackets](http://brackets.io/), [Sublime Text](http://www.sublimetext.com/), [WebStorm](https://www.jetbrains.com/webstorm/), and [Visual Studio](http://www.visualstudio.com/downloads) are popular choices..
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_JAVASCRIPT {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///    &lt;li&gt;Download and install Node.js and npm.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_NODEJS {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_NODEJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven&apos;t already, download and install PHP version 5.6.0 or later.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_PHP {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven&apos;t already, you need to download and install the following tools:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;- Python 3.4.2.&lt;/li&gt;
        ///    &lt;li&gt;- Django 1.7.1.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;Be sure you can run a localhost web server before continuing.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_PYTHON {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_PYTHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you haven’t already, download and install Ruby on Rails. Be sure you can run a localhost web server before continuing.&lt;/p&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_RUBY {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_RUBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    To get set up:
        ///    &lt;ul&gt;
        ///        &lt;li&gt;
        ///            1. Install &lt;a href=&quot;https://www.visualstudio.com/vs-2015-product-editions&quot; target=&quot;_blank&quot;&gt;Visual Studio 2015 Community or Enterprise&lt;/a&gt;.          
        ///        &lt;/li&gt;
        ///        &lt;li&gt;
        ///            2. Verify Windows 10 &lt;a href=&quot;https://msdn.microsoft.com/library/windows/apps/xaml/dn706236.aspx&quot; target=&quot;_blank&quot;&gt;development mode&lt;/a&gt; is enabled. 
        ///        &lt;/li&gt;
        ///        &lt;li&gt;
        ///            3. Make sure that you&apos;ve installed the tools for Windows 10 developmen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_UWP {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    To get set up:
        ///    &lt;ul&gt;
        ///        &lt;li&gt;
        ///            1. Install &lt;a href=&quot;https://www.visualstudio.com/vs-2015-product-editions&quot; target=&quot;_blank&quot;&gt;Visual Studio 2015 Community or Enterprise&lt;/a&gt;.
        ///        &lt;/li&gt;
        ///        &lt;li&gt;
        ///            2. Install &lt;a href=&quot;https://www.xamarin.com/visual-studio&quot; target=&quot;_blank&quot;&gt;Xamarin for Visual Studio&lt;/a&gt;.
        ///        &lt;/li&gt;
        ///        &lt;li&gt;
        ///            3. Verify Windows 10 &lt;a href=&quot;https://msdn.microsoft.com/library/windows/apps/xaml/dn706236.aspx&quot; target=&quot;_blank&quot;&gt;developm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PLATFORM_SETUP_DESCRIPTION_XAMARIN {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_DESCRIPTION_XAMARIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up for Android development.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_ANDROID {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up for Angular development.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_ANGULAR {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_ANGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up for ASP.NET MVC development.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_DOTNET {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_DOTNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up for iOS development.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_IOS {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Before you begin.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_JAVASCRIPT {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up for Node.js development.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_NODEJS {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_NODEJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Get set up for PHP development&lt;/h1&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_PHP {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 id=&quot;before-you-begin&quot;&gt;Get set up for Python development&lt;/h1&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_PYTHON {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_PYTHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 id=&quot;before-you-begin&quot;&gt;Get set up for Ruby development&lt;/h1&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_RUBY {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_RUBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 id=&quot;get-setup&quot;&gt;Get set up for Universal Windows Platform (UWP) development&lt;/h1&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_UWP {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 id=&quot;get-setup&quot;&gt;Get set up for Xamarin development&lt;/h1&gt;.
        /// </summary>
        public static string PLATFORM_SETUP_TITLE_XAMARIN {
            get {
                return ResourceManager.GetString("PLATFORM_SETUP_TITLE_XAMARIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running: Unzip downloaded package, open solution, and run.&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/xamarin&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running: Unzip downloaded package, open solution, and run.&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/aspnetmvc&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_ANDROID {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To run the code sample:&lt;br/&gt;&lt;ul&gt;&lt;li&gt;1. Unzip the downloaded package to a folder, and go to that folder in your command-line tool. &lt;/li&gt;&lt;li&gt;2. Run &lt;b&gt;npm install&lt;/b&gt; and &lt;b&gt;bower install hello&lt;/b&gt; to install project dependencies. &lt;/li&gt;&lt;li&gt;3.Run &lt;b&gt;npm start&lt;/b&gt; and go to &lt;a href=&apos;http://localhost:8080/&apos; target=&apos;_blank&apos;&gt;http://localhost:8080/&lt;/a&gt; in your web browser. &lt;/li&gt;&lt;/ul&gt;&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/plat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_ANGULAR {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_ANGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running: Unzip downloaded package, open solution, and run.&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/aspnetmvc&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_DOTNET {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_DOTNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;1. Unzip the downloaded package. &lt;/li&gt;&lt;li&gt;2. Navigate to the swift or objective-c project folder.&lt;/li&gt;&lt;li&gt;3. Run pod install.&lt;/li&gt;&lt;li&gt;4. Open the workspace in Xcode and run.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/ios&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_IOS_OBJECTIVE_C {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_IOS_OBJECTIVE_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;1. Unzip the downloaded package. &lt;/li&gt;&lt;li&gt;2. Navigate to the swift or objective-c project folder.&lt;/li&gt;&lt;li&gt;3. Run pod install.&lt;/li&gt;&lt;li&gt;4. Open the workspace in Xcode and run.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/ios&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_IOS_SWIFT {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_IOS_SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Your project is on its way from GitHub. To continue: Unzip downloaded package and run..
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_JAVASCRIPT {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running: Unzip downloaded package, change directory to the project and run:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;npm install&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;npm start&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;Then open your browser to the specified port (i.e. &lt;a href=&apos;http://localhost:3000&apos; target=&apos;_blank&apos;&gt;http://localhost:3000&lt;/a&gt;).&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/nodejs&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_NODE {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running:  Unzip downloaded package. Run the command &lt;b&gt;composer install&lt;/b&gt; to install the required dependencies and &lt;b&gt;php –S 0.0.0.0:8000 –t app&lt;/b&gt; to start the web server. Access the app at &lt;a href=&apos;http://localhost:8000&apos; target=&apos;_blank&apos;&gt;http://localhost:8000&lt;/a&gt;.&lt;p&gt;To see how this sample was created, please see our getting started &lt;a href=&apos;http://graph.microsoft.io/en-us/docs/platform/php&apos; target=&apos;_blank&apos;&gt;walkthrough&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_PHP {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running: &lt;br/&gt;&lt;ul&gt;&lt;li&gt;1. Unzip downloaded package, navigate to the folder. &lt;/li&gt;&lt;li&gt;2. Install the &lt;a href=&apos;http://www.python-requests.org/en/latest/&apos; target=&apos;_blank&apos;&gt;Requests: HTTP for Humans&lt;/a&gt; library by running &lt;b&gt;pip install requests&lt;/b&gt;.&lt;/li&gt;&lt;li&gt;3. Run &lt;b&gt;python manage.py migrate&lt;/b&gt; to initialize the database for the app. &lt;/li&gt;&lt;li&gt;4. Then run &lt;b&gt;python manage.py runserver&lt;/b&gt; to start your server.&lt;/li&gt;&lt;li&gt;5. Go to &lt;a href=&apos;http://127.0.0.1:8000&apos; target=&apos;_blank&apos;&gt;http://127.0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_PYTHON {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_PYTHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there! To get it running:&lt;br/&gt;&lt;br/&gt;&lt;ul&gt;&lt;li&gt;1. Unzip downloaded package and go to the folder. &lt;/li&gt;&lt;li&gt;2. If you don&apos;t already  have bundler and rack, you can install them with the following command: &lt;br/&gt;&lt;b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;gem install bundler rack&lt;/b&gt;. &lt;/li&gt;&lt;li&gt;3. Install the Rails application and dependencies with the following command: &lt;br/&gt;&lt;b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;bundle install&lt;/b&gt;&lt;/li&gt;&lt;li&gt;4. To start the Rails application, type the following command: &lt;br /&gt;&lt;b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;ra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string POST_DOWNLOAD_INSTRUCTION_RUBY {
            get {
                return ResourceManager.GetString("POST_DOWNLOAD_INSTRUCTION_RUBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register your app, we will take you to the &lt;i&gt;Microsoft Application Registration portal&lt;/i&gt; where you will be able to get an App ID and redirect URL. You will need either a &lt;a href=&quot;http://dev.office.com/devprogram&quot;&gt;school or work&lt;/a&gt; or &lt;a href=&quot;https://signup.live.com/signup?wa=wsignin1.0&amp;ct=1473983465&amp;rver=6.6.6556.0&amp;wp=MBI_SSL&amp;wreply=https%3a%2f%2foutlook.live.com%2fowa%2f&amp;id=292841&amp;CBCXT=out&amp;cobrandid=90015&amp;bk=1473983466&amp;uiflavor=web&amp;uaid=3b7bae8746264c1bacf1db2b315745cc&amp;mkt=EN-US&amp;lc=1033&amp;lic=1&quot;&gt;Mic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REGISTER_APP_DESCRIPTION {
            get {
                return ResourceManager.GetString("REGISTER_APP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register your app, we will take you to the &lt;i&gt;Microsoft Application Registration portal&lt;/i&gt; where you will be able to get an App ID and redirect URL. You will need either a &lt;a href=&quot;http://dev.office.com/devprogram&quot;&gt;school or work&lt;/a&gt; or &lt;a href=&quot;https://signup.live.com/signup?wa=wsignin1.0&amp;ct=1473983465&amp;rver=6.6.6556.0&amp;wp=MBI_SSL&amp;wreply=https%3a%2f%2foutlook.live.com%2fowa%2f&amp;id=292841&amp;CBCXT=out&amp;cobrandid=90015&amp;bk=1473983466&amp;uiflavor=web&amp;uaid=3b7bae8746264c1bacf1db2b315745cc&amp;mkt=EN-US&amp;lc=1033&amp;lic=1&quot;&gt;Mic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REGISTER_APP_DESCRIPTION_MOBILE {
            get {
                return ResourceManager.GetString("REGISTER_APP_DESCRIPTION_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string REGISTER_APP_NOTE {
            get {
                return ResourceManager.GetString("REGISTER_APP_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*Building an app for enterprise users only?&lt;/b&gt; Use Azure Active Directory V1. Here is &lt;a id=&quot;fineprintlink&quot; style=&quot;cursor: pointer&quot;&gt;why&lt;/a&gt;. &lt;a id=&quot;v1Link&quot; href=&quot;#&quot;&gt;Get Started with this code sample&lt;/a&gt;..
        /// </summary>
        public static string REGISTER_APP_NOTE_MOBILE {
            get {
                return ResourceManager.GetString("REGISTER_APP_NOTE_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter the App Secret that you generated and saved:.
        /// </summary>
        public static string REGISTER_APP_SECRET_PROMPT {
            get {
                return ResourceManager.GetString("REGISTER_APP_SECRET_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering your app. By the way, we also set the Redirect URI on your behalf so it can work with our code sample..
        /// </summary>
        public static string REGISTER_APP_SUCCESS_MSG {
            get {
                return ResourceManager.GetString("REGISTER_APP_SUCCESS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful!.
        /// </summary>
        public static string REGISTER_APP_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_APP_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register the sample app.
        /// </summary>
        public static string REGISTER_APP_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an API, try different values, and choose the Try button to see the responses from a sample tenant..
        /// </summary>
        public static string TRY_OUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TRY_OUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all contacts.
        /// </summary>
        public static string TRY_OUT_GET_CONTACTS_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_CONTACTS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get events.
        /// </summary>
        public static string TRY_OUT_GET_EVENTS_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_EVENTS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get files.
        /// </summary>
        public static string TRY_OUT_GET_FILES_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_FILES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get groups.
        /// </summary>
        public static string TRY_OUT_GET_GROUPS_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_GROUPS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and query strings of group profile.
        /// </summary>
        public static string TRY_OUT_GET_GROUPS_NOTES_TEXT {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_GROUPS_NOTES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get messages.
        /// </summary>
        public static string TRY_OUT_GET_MESSAGE_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_MESSAGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target folder ID or well-known name: Inbox, SentItems, Drafts, or DeletedItems..
        /// </summary>
        public static string TRY_OUT_GET_MESSAGES_NOTES_TEXT {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_MESSAGES_NOTES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get users.
        /// </summary>
        public static string TRY_OUT_GET_USERS_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_USERS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) and query strings of user(s) profile..
        /// </summary>
        public static string TRY_OUT_GET_USERS_NOTES_TEXT {
            get {
                return ResourceManager.GetString("TRY_OUT_GET_USERS_NOTES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TRY_OUT_NAME_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TRY_OUT_NOTES_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_NOTES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it out.
        /// </summary>
        public static string TRY_OUT_TITLE {
            get {
                return ResourceManager.GetString("TRY_OUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try.
        /// </summary>
        public static string TRY_OUT_TRY_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_TRY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TRY_OUT_TYPE_LABEL {
            get {
                return ResourceManager.GetString("TRY_OUT_TYPE_LABEL", resourceCulture);
            }
        }
    }
}
